// Compatibility layer: maps old lucide_icons camelCase names to flutter_lucide snake_case names
// This file exists because lucide_icons 0.257.0 is incompatible with Flutter 3.38+ (IconData is now final)

import 'package:flutter/widgets.dart';
import 'package:flutter_lucide/flutter_lucide.dart' as lucide;

/// Drop-in replacement for the old `LucideIcons` class from `lucide_icons` package.
/// Maps camelCase names to the snake_case names used by `flutter_lucide`.
abstract class LucideIcons {
  static const IconData activity = lucide.LucideIcons.activity;
  static const IconData alertCircle = lucide.LucideIcons.circle_alert;
  static const IconData alertTriangle = lucide.LucideIcons.triangle_alert;
  static const IconData arrowLeft = lucide.LucideIcons.arrow_left;
  static const IconData arrowRight = lucide.LucideIcons.arrow_right;
  static const IconData award = lucide.LucideIcons.award;
  static const IconData ban = lucide.LucideIcons.ban;
  static const IconData barChart2 = lucide.LucideIcons.chart_column;
  static const IconData bell = lucide.LucideIcons.bell;
  static const IconData briefcase = lucide.LucideIcons.briefcase;
  static const IconData building = lucide.LucideIcons.building;
  static const IconData building2 = lucide.LucideIcons.building_2;
  static const IconData cake = lucide.LucideIcons.cake;
  static const IconData calendar = lucide.LucideIcons.calendar;
  static const IconData calendarClock = lucide.LucideIcons.calendar_clock;
  static const IconData calendarDays = lucide.LucideIcons.calendar_days;
  static const IconData calendarX = lucide.LucideIcons.calendar_x;
  static const IconData car = lucide.LucideIcons.car;
  static const IconData checkCircle = lucide.LucideIcons.circle_check;
  static const IconData checkCircle2 = lucide.LucideIcons.circle_check;
  static const IconData checkSquare = lucide.LucideIcons.square_check;
  static const IconData chevronDown = lucide.LucideIcons.chevron_down;
  static const IconData chevronRight = lucide.LucideIcons.chevron_right;
  static const IconData clock = lucide.LucideIcons.clock;
  static const IconData copy = lucide.LucideIcons.copy;
  static const IconData cpu = lucide.LucideIcons.cpu;
  static const IconData creditCard = lucide.LucideIcons.credit_card;
  static const IconData dollarSign = lucide.LucideIcons.dollar_sign;
  static const IconData edit3 = lucide.LucideIcons.pencil;
  static const IconData eye = lucide.LucideIcons.eye;
  static const IconData eyeOff = lucide.LucideIcons.eye_off;
  static const IconData fileMinus = lucide.LucideIcons.file_minus;
  static const IconData filePlus = lucide.LucideIcons.file_plus;
  static const IconData fileSearch = lucide.LucideIcons.file_search;
  static const IconData fileText = lucide.LucideIcons.file_text;
  static const IconData hash = lucide.LucideIcons.hash;
  static const IconData headphones = lucide.LucideIcons.headphones;
  static const IconData heart = lucide.LucideIcons.heart;
  static const IconData home = lucide.LucideIcons.house;
  static const IconData inbox = lucide.LucideIcons.inbox;
  static const IconData indianRupee = lucide.LucideIcons.indian_rupee;
  static const IconData info = lucide.LucideIcons.info;
  static const IconData landmark = lucide.LucideIcons.landmark;
  static const IconData layoutGrid = lucide.LucideIcons.layout_grid;
  static const IconData leaf = lucide.LucideIcons.leaf;
  static const IconData list = lucide.LucideIcons.list;
  static const IconData lock = lucide.LucideIcons.lock;
  static const IconData logOut = lucide.LucideIcons.log_out;
  static const IconData mail = lucide.LucideIcons.mail;
  static const IconData mapPin = lucide.LucideIcons.map_pin;
  static const IconData messageCircle = lucide.LucideIcons.message_circle;
  static const IconData messageSquare = lucide.LucideIcons.message_square;
  static const IconData moon = lucide.LucideIcons.moon;
  static const IconData navigation = lucide.LucideIcons.navigation;
  static const IconData pauseCircle = lucide.LucideIcons.circle_pause;
  static const IconData phone = lucide.LucideIcons.phone;
  static const IconData phoneCall = lucide.LucideIcons.phone_call;
  static const IconData pieChart = lucide.LucideIcons.chart_pie;
  static const IconData plane = lucide.LucideIcons.plane;
  static const IconData plus = lucide.LucideIcons.plus;
  static const IconData qrCode = lucide.LucideIcons.qr_code;
  static const IconData receipt = lucide.LucideIcons.receipt;
  static const IconData refreshCw = lucide.LucideIcons.refresh_cw;
  static const IconData scale = lucide.LucideIcons.scale;
  static const IconData search = lucide.LucideIcons.search;
  static const IconData settings = lucide.LucideIcons.settings;
  static const IconData share2 = lucide.LucideIcons.share_2;
  static const IconData shield = lucide.LucideIcons.shield;
  static const IconData shieldCheck = lucide.LucideIcons.shield_check;
  static const IconData shieldOff = lucide.LucideIcons.shield_off;
  static const IconData store = lucide.LucideIcons.store;
  static const IconData tag = lucide.LucideIcons.tag;
  static const IconData target = lucide.LucideIcons.target;
  static const IconData trendingUp = lucide.LucideIcons.trending_up;
  static const IconData upload = lucide.LucideIcons.upload;
  static const IconData user = lucide.LucideIcons.user;
  static const IconData userCheck = lucide.LucideIcons.user_check;
  static const IconData userMinus = lucide.LucideIcons.user_minus;
  static const IconData userPlus = lucide.LucideIcons.user_plus;
  static const IconData users = lucide.LucideIcons.users;
  static const IconData wallet = lucide.LucideIcons.wallet;
  static const IconData wifiOff = lucide.LucideIcons.wifi_off;
  static const IconData wrench = lucide.LucideIcons.wrench;
  static const IconData x = lucide.LucideIcons.x;
  static const IconData xCircle = lucide.LucideIcons.circle_x;
  static const IconData zap = lucide.LucideIcons.zap;
  static const IconData globe = lucide.LucideIcons.globe;
  static const IconData fileCheck = lucide.LucideIcons.file_check;
  static const IconData trash2 = lucide.LucideIcons.trash_2;
  static const IconData truck = lucide.LucideIcons.truck;
  static const IconData check = lucide.LucideIcons.check;
  static const IconData fuel = lucide.LucideIcons.fuel;
  static const IconData calendarCheck = lucide.LucideIcons.calendar_check;
}
